name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node (or other build tools if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Als je een buildproces hebt (zoals npm run build), voer dat dan hier uit
      # Bijvoorbeeld:
      # - name: Build static content
      #   run: npm run build

      # Zet de bestanden in de gewenste map (bijvoorbeeld ai/)
      - name: Move files to ai folder
        run: |
          mkdir -p ai
          cp -r * ai/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './ai'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
